#!/usr/bin/env zsh 

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Ask LLAMA3 
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 🦙
# @raycast.argument1 { "type": "text", "placeholder": "Question" }
# @raycast.packageName llm-ask-llama3

# Documentation:
# @raycast.description Asks a question to LLAMA3-8B model 
# @raycast.author zmactep
# @raycast.authorURL https://raycast.com/zmactep

LLAMA3="llama3:8b-instruct-q8_0"

ollama run $LLAMA3 $1
